{% set name = "autodynatrace" %}
{% set version = "1.0.86" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autodynatrace-{{ version }}.tar.gz
  sha256: b6af86d29f402f26986295eebf41c0ce6df7d5b341f4ea30e96511cb2ca8c888

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autowrapt >=1.0
    - oneagent-sdk >=1.3.0
    - python >=3.6
    - six >=1.10.0
    - wrapt >=1.11.2

test:
  imports:
    - autodynatrace
    - autodynatrace.wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dlopes7/autodynatrace
  summary: Auto instrumentation for the OneAgent SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
