schema_version: 1

context:
  name: autodynatrace
  version: 2.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/autodynatrace-${{ version }}.tar.gz
  sha256: b503e7c46c67c316a2986f83b96692870d82ac7c9d28df001ea62f7cff9a41a2

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - autowrapt >=1.0
    - oneagent-sdk >=1.3.0
    - python >=${{ python_min }}
    - six >=1.10.0
    - wrapt >=1.11.2

tests:
  - python:
      imports:
        - autodynatrace
        - autodynatrace.wrappers
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Auto instrumentation for the OneAgent SDK
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dlopes7/autodynatrace

extra:
  recipe-maintainers:
    - janjagusch
